### ISSUE TITLE
Dynamically load test parameters?

### ISSUE THREAD

**Issue by gregory-h** [ryym/mocha-each#3]
I'm trying to set test parameters dynamically with no joy and not sure why. For example I would think that removing the comments around the before() function should produce the same result but it does not - the forEach(tests) block executes with an empty array. ???

const assert = require('assert');
const forEach = require('mocha-each');
 
function add(a, b) {
  return parseInt(a) + parseInt(b);
}

var tests = []

describe('add()', () => {

  //before(function(done) {
    tests = [
      [1, 1, 2],
      [2, -2, 0],
      [140, 48, 188]
    ]; 
    //done()
  //})

  describe('should wait for before', function(done) {

    forEach(tests)
    .it('adds %d and %d then returns %d', (left, right, expected) => {
      assert.equal(add(left, right), expected);
    });
   
    context('with invalid arguments', () => {
      forEach([
        [1, 'foo'],
        [null, 10],
        [{}, []]
      ])
      .it('adds %j and %j then returns NaN', (left, right,done) => {
        const value = add(left, right);
        assert(isNaN(value));
        done()
      });
    });

  })

});

**Comment by ryym** [comment]
Unfortunately, you can't load parameters dynamically using a `before` hook because a callback registered by the `before` is always executed after the `forEach` function. They are in different phases.

First, Mocha loads test scripts and executes test-definer functions like `describe`, `it` or `before` which registers a callback (phase 1). For instance `before` registers a hook callback but the callback itself is not executed in this phase.
After the phase 1 these callbacks are actually executed in a proper order (phase 2).
So, the `forEach` and `before` function itself are run in phase 1 but a callback registered by the `before` is run in phase 2. This is why you can't prepare parameters using `before` hook.

**Comment by gregory-h** [comment]
Thanks for clarifying - I need to look deeper into Mocha. 

I notice that a simple async functional call also isn't sufficient; is there any way that you're aware of?

**Comment by ryym** [comment]
If you want to generate parameterized tests asynchronously, maybe you can use [`--delay`](http://mochajs.org/#delayed-root-suite) option. Using this, you can define tests after some asynchronous process like this:

```js
const assert = require('assert')
const forEach = require('mocha-each')

new Promise(resolve => {
  setTimeout(() => {
    resolve([1, 2, 3])
  }, 1000)
})
.then(params => {

  // Define tests.
  describe('async test', () => {
    forEach(params).it('is a number (%d)', i => {
      assert(i > 0)
    })
  })

  // Run the tests explicitly.
  run()
})
```

output:

```
% mocha --delay test.js

  async test
    ✓ is a number (1)
    ✓ is a number (2)
    ✓ is a number (3)

  3 passing (11ms)
```
